In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('employee.xlsx')

In [ ]:
df.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT

### 1. write code to create a new column that is the sum of two existing columns age & salary.

In [ ]:
df['Sum'] = df['Age'] + df['Annual Salary']

In [ ]:
df['Sum']

0      141659
1      100034
2      163149
3       84939
4       95464
        ...
995     98460
996     47431
997    176741
998     95993
999    216258
Name: Sum, Length: 1000, dtype: int64

### 2. filter out rows where: The salary is less than 50,000. The department is not "Finance".

In [ ]:
df[(df['Annual Salary'] < 50000) & (df['Department'] != 'Finance')]

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Sum
23,E00671,Leonardo Dixon,Analyst,Sales,Speciality Products,Male,Caucasian,37,2019-09-05,49998,0.0,United States,Seattle,NaT,50035
85,E01516,Willow Mai,Business Partner,Human Resources,Manufacturing,Female,Asian,45,2003-12-17,48345,0.0,China,Chengdu,NaT,48390
133,E03849,Evelyn Jung,Analyst,Sales,Research & Development,Female,Asian,30,2021-02-14,48340,0.0,China,Beijing,NaT,48370
180,E01361,Emma Hill,IT Coordinator,IT,Manufacturing,Female,Caucasian,54,2016-12-27,41673,0.0,United States,Miami,NaT,41727
182,E03719,Jack Brown,Analyst,Marketing,Corporate,Male,Caucasian,55,2004-12-07,40752,0.0,United States,Phoenix,NaT,40807
185,E00671,Miles Cho,Systems Analyst,IT,Speciality Products,Male,Asian,47,1999-03-10,49404,0.0,China,Beijing,NaT,49451
201,E02183,Sarah Ayala,Analyst,Sales,Corporate,Female,Latino,47,2015-06-09,41429,0.0,United States,Seattle,NaT,41476
262,E04386,Cameron Powell,Business Partner,Human Resources,Manufacturing,Male,Black,41,2004-08-20,49186,0.0,United States,Austin,2008-06-17,49227
277,E02062,Nora Santiago,Analyst,Accounting,Research & Development,Female,Latino,55,1996-06-26,48687,0.0,Brazil,Rio de Janerio,NaT,48742
280,E00691,Avery Yee,Systems Analyst,IT,Manufacturing,Female,Asian,34,2016-05-22,44614,0.0,United States,Miami,NaT,44648
291,E02252,Lillian Park,Analyst,Marketing,Research & Development,Female,Asian,40,2021-02-24,46833,0.0,China,Chengdu,2021-11-10,46873
307,E01466,Connor Vang,Analyst,Sales,Speciality Products,Male,Asian,25,2021-07-28,46845,0.0,United States,Miami,NaT,46870
393,E02023,Maverick Mehta,Systems Analyst,IT,Manufacturing,Male,Asian,40,2007-07-30,41859,0.0,United States,Seattle,NaT,41899
409,E02044,Caroline Alexander,Business Partner,Human Resources,Manufacturing,Female,Black,42,2020-09-18,47071,0.0,United States,Columbus,NaT,47113
428,E04041,Clara Huynh,IT Coordinator,IT,Speciality Products,Female,Asian,39,2020-11-18,48415,0.0,China,Shanghai,NaT,48454
459,E03461,Nathan Lau,Business Partner,Human Resources,Research & Development,Male,Asian,35,2011-02-22,43336,0.0,United States,Austin,2020-07-12,43371
490,E00403,Liliana Soto,Business Partner,Human Resources,Manufacturing,Female,Latino,58,2010-10-12,43001,0.0,United States,Austin,NaT,43059
509,E03223,Ethan Joseph,IT Coordinator,IT,Research & Development,Male,Caucasian,45,2018-05-28,49219,0.0,United States,Columbus,NaT,49264
519,E02531,Jameson Foster,Analyst,Marketing,Manufacturing,Male,Caucasian,28,2021-07-18,43391,0.0,United States,Columbus,NaT,43419
603,E03571,Lincoln Henderson,Business Partner,Human Resources,Speciality Products,Male,Caucasian,28,2021-06-27,48510,0.0,United States,Chicago,NaT,48538
616,E02857,Valentina Davis,Analyst,Sales,Speciality Products,Female,Caucasian,33,2014-04-13,46878,0.0,United States,Miami,NaT,46911
624,E01432,Peyton Garza,Systems Analyst,IT,Manufacturing,Female,Latino,53,2004-08-15,44735,0.0,Brazil,Manaus,NaT,44788
660,E02562,Christian Medina,Analyst,Marketing,Corporate,Male,Latino,51,2007-06-19,45206,0.0,United States,Columbus,NaT,45257
681,E03655,Samantha Rogers,Analyst,Marketing,Speciality Products,Female,Caucasian,28,2020-01-17,45061,0.0,United States,Miami,NaT,45089
693,E01877,Abigail Garza,Analyst,Accounting,Manufacturing,Female,Latino,33,2018-05-27,45049,0.0,United States,Seattle,NaT,45082
698,E00145,Kinsley Dixon,Analyst,Accounting,Manufacturing,Female,Caucasian,28,2019-05-25,45819,0.0,United States,Miami,NaT,45847
721,E03227,Eli Richardson,IT Coordinator,IT,Speciality Products,Male,Caucasian,38,2015-04-19,48762,0.0,United States,Seattle,NaT,48800
736,E02798,Charles Henderson,Systems Analyst,IT,Speciality Products,Male,Caucasian,48,2002-02-11,43080,0.0,United States,Austin,NaT,43128
765,E00951,Everly Lin,Business Partner,Human Resources,Manufacturing,Female,Asian,25,2021-03-15,47974,0.0,China,Chongqing,NaT,47999
776,E01895,Gabriel Zhou,IT Coordinator,IT,Manufacturing,Male,Asian,25,2021-01-17,41844,0.0,China,Chongqing,NaT,41869
781,E03928,Miles Dang,IT Coordinator,IT,Speciality Products,Male,Asian,61,2000-09-24,40063,0.0,United States,Miami,NaT,40124
782,E04109,Leah Bryant,IT Coordinator,IT,Manufacturing,Female,Caucasian,55,2004-04-30,40124,0.0,United States,Austin,NaT,40179
787,E02732,Alice Tran,Analyst,Marketing,Corporate,Female,Asian,39,2014-07-29,40897,0.0,United States,Seattle,NaT,40936
823,E00862,Levi Moreno,Systems Analyst,IT,Research & Development,Male,Latino,64,2020-06-27,40316,0.0,Brazil,Manaus,NaT,40380
847,E01388,Cooper Gupta,Business Partner,Human Resources,Speciality Products,Male,Asian,58,2014-06-20,41728,0.0,China,Chongqing,NaT,41786
854,E00568,Ian Vargas,Analyst,Sales,Manufacturing,Male,Latino,26,2021-03-02,44732,0.0,Brazil,Rio de Janerio,NaT,44758
888,E03455,Hadley Ford,Systems Analyst,IT,Research & Development,Female,Caucasian,52,2005-02-23,45286,0.0,United States,Chicago,NaT,45338
891,E01264,Hazel Alvarez,Business Partner,Human Resources,Research & Development,Female,Latino,62,2014-04-19,45295,0.0,Brazil,Sao Paulo,NaT,45357
894,E00480,Hadley Yee,Business Partner,Human Resources,Speciality Products,Female,Asian,31,2018-03-12,47913,0.0,United States,Seattle,NaT,47944
895,E00203,Julia Doan,Business Partner,Human Resources,Speciality Products,Female,Asian,53,2017-09-07,46727,0.0,United States,Columbus,2018-05-31,46780
907,E01895,Peyton Walker,Analyst,Marketing,Research & Development,Female,Caucasian,43,2019-07-13,41545,0.0,United States,Miami,NaT,41588
994,E01148,Scarlett Kumar,Systems Analyst,IT,Corporate,Female,Asian,55,2009-01-07,47032,0.0,United States,Columbus,NaT,47087

### 3. write code to Replace missing values in a specific column with the mean of that column.

In [ ]:
df.isnull().sum()

EEID               0
Full Name          0
Job Title          0
Department         0
Business Unit      0
Gender             0
Ethnicity          0
Age                0
Hire Date          0
Annual Salary      0
Bonus %            0
Country            0
City               0
Exit Date        915
Sum                0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EEID           1000 non-null   object
 1   Full Name      1000 non-null   object
 2   Job Title      1000 non-null   object
 3   Department     1000 non-null   object
 4   Business Unit  1000 non-null   object
 5   Gender         1000 non-null   object
 6   Ethnicity      1000 non-null   object
 7   Age            1000 non-null   int64
 8   Hire Date      1000 non-null   datetime64[ns]
 9   Annual Salary  1000 non-null   int64
 10  Bonus %        1000 non-null   float64
 11  Country        1000 non-null   object
 12  City           1000 non-null   object
 13  Exit Date      85 non-null     datetime64[ns]
 14  Sum            1000 non-null   int64
dtypes: datetime64[ns](2), float64(1), int64(3), object(9)
memory usage: 117.3+ KB

In [ ]:
df['Exit Date'].fillna(df['Exit Date'].mode()[0], inplace=True)

<ipython-input-9-7cf2c3b47668>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Exit Date'].fillna(df['Exit Date'].mode()[0], inplace=True)

In [ ]:
df.isnull().sum()

EEID             0
Full Name        0
Job Title        0
Department       0
Business Unit    0
Gender           0
Ethnicity        0
Age              0
Hire Date        0
Annual Salary    0
Bonus %          0
Country          0
City             0
Exit Date        0
Sum              0
dtype: int64

### 4. Write down the code to find the maximum salary for each region.

In [ ]:
max_salary_by_region = df.groupby('Country')['Annual Salary'].max()
max_salary_by_region

Country
Brazil           258426
China            257194
United States    258498
Name: Annual Salary, dtype: int64

### 5. write code to create 3 saperate column date, month, year from datetime column in review data.

In [ ]:
rdf = pd.read_csv('review_data.csv')
rdf.head()

,name,review,title,rating,datetime
0,Certified Refurbished Amazon Fire TV (Previous...,I'm your typical middle-aged woman - I don't g...,"A review from a non-techie 11,064 people found...",2,01-01-2023
1,Kindle Keyboard,"I'm a first-time Kindle owner, so I have nothi...","I Wanted a Dedicated E-Reader, and That's What...",3,01-06-2023
2,Kindle Keyboard,It simply works even after 3.5 years of consta...,Do I need to say anything more?,5,01-09-2023
3,Kindle Keyboard,UPDATE NOVEMBER 2011:br /br /My review is now ...,Kindle vs. Nook (updated),1,01-11-2023
4,Certified Refurbished Amazon Fire TV (Previous...,I'm your typical middle-aged woman - I don't g...,"A review from a non-techie 11,059 people found...",4,01-11-2023

In [ ]:
rdf['day'] = pd.DatetimeIndex(rdf['datetime']).day
rdf['month'] = pd.DatetimeIndex(rdf['datetime']).month
rdf['year'] = pd.DatetimeIndex(rdf['datetime']).year

In [ ]:
rdf.head()

,name,review,title,rating,datetime,day,month,year
0,Certified Refurbished Amazon Fire TV (Previous...,I'm your typical middle-aged woman - I don't g...,"A review from a non-techie 11,064 people found...",2,01-01-2023,1,1,2023
1,Kindle Keyboard,"I'm a first-time Kindle owner, so I have nothi...","I Wanted a Dedicated E-Reader, and That's What...",3,01-06-2023,6,1,2023
2,Kindle Keyboard,It simply works even after 3.5 years of consta...,Do I need to say anything more?,5,01-09-2023,9,1,2023
3,Kindle Keyboard,UPDATE NOVEMBER 2011:br /br /My review is now ...,Kindle vs. Nook (updated),1,01-11-2023,11,1,2023
4,Certified Refurbished Amazon Fire TV (Previous...,I'm your typical middle-aged woman - I don't g...,"A review from a non-techie 11,059 people found...",4,01-11-2023,11,1,2023

### 6. write code to Count the number of words in each review with a reviews column in reviwe dataset:

In [ ]:
rdf['count_words_in_review'] = rdf['review'].count()

In [ ]:
rdf.head()

,name,review,title,rating,datetime,day,month,year,count_words_in_review
0,Certified Refurbished Amazon Fire TV (Previous...,I'm your typical middle-aged woman - I don't g...,"A review from a non-techie 11,064 people found...",2,01-01-2023,1,1,2023,106
1,Kindle Keyboard,"I'm a first-time Kindle owner, so I have nothi...","I Wanted a Dedicated E-Reader, and That's What...",3,01-06-2023,6,1,2023,106
2,Kindle Keyboard,It simply works even after 3.5 years of consta...,Do I need to say anything more?,5,01-09-2023,9,1,2023,106
3,Kindle Keyboard,UPDATE NOVEMBER 2011:br /br /My review is now ...,Kindle vs. Nook (updated),1,01-11-2023,11,1,2023,106
4,Certified Refurbished Amazon Fire TV (Previous...,I'm your typical middle-aged woman - I don't g...,"A review from a non-techie 11,059 people found...",4,01-11-2023,11,1,2023,106

### 7. Split it name column into two new columns: `first_name` and `last_name`.

In [ ]:
df[['first_name', 'last_name']] = df['Full Name'].str.split(' ', n=1, expand=True)

In [ ]:
df.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Sum,first_name,last_name
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16,141659,Emily,Davis
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,2020-07-17,100034,Theodore,Dinh
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,2020-07-17,163149,Luna,Sanders
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,2020-07-17,84939,Penelope,Jordan
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,2020-07-17,95464,Austin,Vo

### 8. Create a new column performance: If `salary > 10000`, set it to "High".

In [ ]:
df['Performance'] = np.where(df['Annual Salary'] > 10000, "High", "")
df.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Sum,first_name,last_name,Performance
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16,141659,Emily,Davis,High
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,2020-07-17,100034,Theodore,Dinh,High
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,2020-07-17,163149,Luna,Sanders,High
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,2020-07-17,84939,Penelope,Jordan,High
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,2020-07-17,95464,Austin,Vo,High

### 9. how to identify duplicate & drop duplicates keeping only the first occurrence using pandas.

In [ ]:
duplicate_rows = df[df.duplicated()]

df_no_duplicates = df.drop_duplicates(keep='first')

In [ ]:
duplicate_rows

Empty DataFrame
Columns: [EEID, Full Name, Job Title, Department, Business Unit, Gender, Ethnicity, Age, Hire Date, Annual Salary, Bonus %, Country, City, Exit Date, Sum, first_name, last_name, Performance]
Index: []

In [ ]:
df_no_duplicates.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Sum,first_name,last_name,Performance
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16,141659,Emily,Davis,High
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,2020-07-17,100034,Theodore,Dinh,High
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,2020-07-17,163149,Luna,Sanders,High
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,2020-07-17,84939,Penelope,Jordan,High
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,2020-07-17,95464,Austin,Vo,High

### 10. write code to create new column name_length to calculate length of name using apply in employee dataset.

In [ ]:
df['name_length'] = df['Full Name'].apply(len)

In [ ]:
df.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Sum,first_name,last_name,Performance,name_length
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16,141659,Emily,Davis,High,11
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,2020-07-17,100034,Theodore,Dinh,High,13
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,2020-07-17,163149,Luna,Sanders,High,12
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,2020-07-17,84939,Penelope,Jordan,High,15
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,2020-07-17,95464,Austin,Vo,High,9