### Experiment 2 → Lower Case

In [1]:
sentence = "Hello, This is cat"

In [2]:
sentence

'Hello, This is cat'

In [3]:
lower_case = sentence.lower()

In [4]:
lower_case

'hello, this is cat'

In [5]:
sentence_list = ['Could you BUY a coffee',
                'It is impossible TO find a hotel',
                'i want a apple']
sentence_list

['Could you BUY a coffee',
 'It is impossible TO find a hotel',
 'i want a apple']

In [6]:
lower_case_list = [i.lower() for i in sentence_list]

In [7]:
lower_case_list

['could you buy a coffee',
 'it is impossible to find a hotel',
 'i want a apple']

In [8]:
x = """Never, never begin a story this way when you write one. 
No opening could possibly be worse. 
It is unimaginative, flat, dry and likely to consist of mere wind. 
But in this instance it is allowable. 
For the following paragraph, which should have inaugurated the narrative, 
is too wildly extravagant and preposterous to be flaunted in the face of the reader without preparation."""

In [9]:
new_x = x.lower()

In [10]:
new_x

'never, never begin a story this way when you write one. \nno opening could possibly be worse. \nit is unimaginative, flat, dry and likely to consist of mere wind. \nbut in this instance it is allowable. \nfor the following paragraph, which should have inaugurated the narrative, \nis too wildly extravagant and preposterous to be flaunted in the face of the reader without preparation.'

## Experiment 3 → NLTK (Tokenization)

In [11]:
import nltk

In [12]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to C:\Users\Dharm Singh
[nltk_data]     Saini\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [13]:
from nltk.tokenize import word_tokenize, sent_tokenize

#### Sentence tokenization

In [14]:
sentences = "It was a day in March. Sarah was crying over her bill of fare."
sent_tokenize(sentences)

['It was a day in March.', 'Sarah was crying over her bill of fare.']

#### Word tokenization

In [15]:
sentence2 = "It was a day in March."
word_tokenize(sentence2)

['It', 'was', 'a', 'day', 'in', 'March', '.']

In [16]:
sentence3 = "Sarah was crying over her bill of fare."

In [17]:
word_tokenize(sentence3)

['Sarah', 'was', 'crying', 'over', 'her', 'bill', 'of', 'fare', '.']

In [18]:
text = "Never begin a story this way when you write one. No opening could possibly be worse. It is unimaginative, flat, dry and likely to consist of mere wind. But in this instance it is allowable. For the following paragraph, which should have inaugurated the narrative, is too wildly extravagant and preposterous to be flaunted in the face of the reader without preparation."

In [19]:
text

'Never begin a story this way when you write one. No opening could possibly be worse. It is unimaginative, flat, dry and likely to consist of mere wind. But in this instance it is allowable. For the following paragraph, which should have inaugurated the narrative, is too wildly extravagant and preposterous to be flaunted in the face of the reader without preparation.'

In [20]:
text.split('.')

['Never begin a story this way when you write one',
 ' No opening could possibly be worse',
 ' It is unimaginative, flat, dry and likely to consist of mere wind',
 ' But in this instance it is allowable',
 ' For the following paragraph, which should have inaugurated the narrative, is too wildly extravagant and preposterous to be flaunted in the face of the reader without preparation',
 '']

In [21]:
text.split()

['Never',
 'begin',
 'a',
 'story',
 'this',
 'way',
 'when',
 'you',
 'write',
 'one.',
 'No',
 'opening',
 'could',
 'possibly',
 'be',
 'worse.',
 'It',
 'is',
 'unimaginative,',
 'flat,',
 'dry',
 'and',
 'likely',
 'to',
 'consist',
 'of',
 'mere',
 'wind.',
 'But',
 'in',
 'this',
 'instance',
 'it',
 'is',
 'allowable.',
 'For',
 'the',
 'following',
 'paragraph,',
 'which',
 'should',
 'have',
 'inaugurated',
 'the',
 'narrative,',
 'is',
 'too',
 'wildly',
 'extravagant',
 'and',
 'preposterous',
 'to',
 'be',
 'flaunted',
 'in',
 'the',
 'face',
 'of',
 'the',
 'reader',
 'without',
 'preparation.']

### Experiment 4 → Regular Expression

In [22]:
import re

In [23]:
my_folder = r"C:\desktop\notes" # r mean str
print(my_folder)

C:\desktop\notes

In [24]:
res_search = re.search("could","No opening could possibly be worse")
res_search

In [25]:
res_search.group()

'could'

In [26]:
string = "sarah was able to help me find the items i needed quickly"

In [27]:
new_str = re.sub(r"sarah", r"sara", string)
new_str

'sara was able to help me find the items i needed quickly'

In [28]:
customer_reviews = ['sam was a great help to me in the store', 
                    'the cashier was very rude to me, I think her name was eleanor', 
                    'amazing work from sadeen!', 
                    'sarah was able to help me find the items i needed quickly', 
                    'lucy is such a great addition to the team', 
                    'great service from sara she found me what i wanted'
                   ]

only sarah's review

In [29]:
sarah_review = []
pattern_to_find = r"sarah?"

In [30]:
for string in customer_reviews:
    if(re.search(pattern_to_find, string)):
        sarah_review.append(string)

In [31]:
sarah_review

['sarah was able to help me find the items i needed quickly',
 'great service from sara she found me what i wanted']

#### review that start with the letter a

In [32]:
a_review = []
pattern_to_find_a = r"^a"

In [33]:
for string in customer_reviews:
    if(re.search(pattern_to_find_a, string)):
        a_review.append(string)

In [34]:
a_review

['amazing work from sadeen!']

#### review that end with the letter a

In [35]:
y_review = []
pattern_to_find_y = r"y$"

In [36]:
for string in customer_reviews:
    if(re.search(pattern_to_find_y, string)):
        y_review.append(string)

In [37]:
y_review

['sarah was able to help me find the items i needed quickly']

#### review that contains the words need or wanted

In [38]:
need_review = []
pattern_to_find_need = r"(need|want)ed"

In [39]:
for string in customer_reviews:
    if(re.search(pattern_to_find_need, string)):
        need_review.append(string)

In [40]:
need_review

['sarah was able to help me find the items i needed quickly',
 'great service from sara she found me what i wanted']

In [41]:
no_punct_review = []
pattern_to_find_no_punct = r"^w\s"

In [42]:
for string in customer_reviews:
    if(re.sub(pattern_to_find_no_punct,"", string)):
        no_punct_review.append(string)

In [43]:
no_punct_review

['sam was a great help to me in the store',
 'the cashier was very rude to me, I think her name was eleanor',
 'amazing work from sadeen!',
 'sarah was able to help me find the items i needed quickly',
 'lucy is such a great addition to the team',
 'great service from sara she found me what i wanted']

### Experiment 5

In [44]:
from nltk.stem import PorterStemmer

In [45]:
ps = PorterStemmer()

In [46]:
connect_tokens = ["connecting", "connected", "connectivity", "connection", "conectable", "connects", "connect"]

In [47]:
for t in connect_tokens:
    print(t, " : ", ps.stem(t))

connecting  :  connect
connected  :  connect
connectivity  :  connect
connection  :  connect
conectable  :  conect
connects  :  connect
connect  :  connect

In [48]:
learn_tokens = ["leaning", "learned", "learns", "learn", "learners"]

In [49]:
for l in learn_tokens:
    print(l, " : ", ps.stem(l))

leaning  :  lean
learned  :  learn
learns  :  learn
learn  :  learn
learners  :  learner

In [50]:
likes_tokens = ["liked", "better", "worse"]

In [51]:
for l in likes_tokens:
    print(l, " : ", ps.stem(l))

liked  :  like
better  :  better
worse  :  wors

In [52]:
win_tokens = ["wins", "wining", "wined", "win"]

In [53]:
for w in win_tokens:
    print(w, " : ", ps.stem(w))

wins  :  win
wining  :  wine
wined  :  wine
win  :  win

### Experiment 6 → Stemming

In [54]:
import nltk

In [55]:
nltk.download("wordnet")
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to C:\Users\Dharm Singh
[nltk_data]     Saini\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [56]:
lemmatizer = WordNetLemmatizer()

In [57]:
for t in connect_tokens:
    print(t, " : ", lemmatizer.lemmatize(t))

connecting  :  connecting
connected  :  connected
connectivity  :  connectivity
connection  :  connection
conectable  :  conectable
connects  :  connects
connect  :  connect

In [58]:
for t in learn_tokens:
    print(t, " : ", lemmatizer.lemmatize(t))

leaning  :  leaning
learned  :  learned
learns  :  learns
learn  :  learn
learners  :  learner

In [59]:
for t in likes_tokens:
    print(t, " : ", lemmatizer.lemmatize(t))

liked  :  liked
better  :  better
worse  :  worse

In [60]:
words = ["running", "flies", "better", "ate", "amazing"]

In [61]:
for t in words:
    print(t, " : ", lemmatizer.lemmatize(t))

running  :  running
flies  :  fly
better  :  better
ate  :  ate
amazing  :  amazing

### Experiment 7 → Bag of Words

In [62]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [63]:
data = [' Most shark attacks occur about 10 feet from the beach since that is where the people are',
        'the efficiency with which he paired the socks in the drawer was quite admirable',
        'carol drank the blood as if she were a vampire',
        'giving directions that the mountains are to the west only works when you can see them',
        'the sign said there was road work ahead so he decided to speed up',
        'the gruff old man sat in the back of the bait shop grumbling to himself as he scooped out a handful of worms']

In [64]:
countvec = CountVectorizer()

In [65]:
countvet_fit = countvec.fit_transform(data)

In [66]:
bag_of_words = pd.DataFrame(countvet_fit.toarray(), columns = countvec.get_feature_names_out())

In [67]:
bag_of_words

,10,about,admirable,ahead,are,as,attacks,back,bait,beach,...,were,west,when,where,which,with,work,works,worms,you
0,1,1,0,0,1,0,1,0,0,1,...,0,0,0,1,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,0,0,0,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,1,0

#### TF-IDF

In [68]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [69]:
data = [' Most shark attacks occur about 10 feet from the beach since that is where the people are',
        'the efficiency with which he paired the socks in the drawer was quite admirable',
        'carol drank the blood as if she were a vampire',
        'giving directions that the mountains are to the west only works when you can see them',
        'the sign said there was road work ahead so he decided to speed up',
        'the gruff old man sat in the back of the bait shop grumbling to himself as he scooped out a handful of worms']

In [70]:
tfidfVec = TfidfVectorizer()

In [71]:
tfidfVec_fit = tfidfVec.fit_transform(data)

In [72]:
tfidfVec_bag_of_words = pd.DataFrame(tfidfVec_fit.toarray(), columns = tfidfVec.get_feature_names_out())

In [73]:
tfidfVec_bag_of_words

,10,about,admirable,ahead,are,as,attacks,back,bait,beach,...,were,west,when,where,which,with,work,works,worms,you
0,0.257061,0.257061,0.000000,0.000000,0.210794,0.000000,0.257061,0.00000,0.00000,0.257061,...,0.000000,0.00000,0.00000,0.257061,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000
1,0.000000,0.000000,0.293641,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.00000,0.00000,0.000000,0.293641,0.293641,0.000000,0.00000,0.00000,0.00000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.292313,0.000000,0.00000,0.00000,0.000000,...,0.356474,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000
3,0.000000,0.000000,0.000000,0.000000,0.222257,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.27104,0.27104,0.000000,0.000000,0.000000,0.000000,0.27104,0.00000,0.27104
4,0.000000,0.000000,0.000000,0.290766,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.290766,0.00000,0.00000,0.00000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.178615,0.000000,0.21782,0.21782,0.000000,...,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.21782,0.00000

### Experiment 8 → StopWords

In [74]:
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to C:\Users\Dharm Singh
[nltk_data]     Saini\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [75]:
en_stopwords = stopwords.words('english')

In [76]:
en_stopwords

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [77]:
sentence5 = "Its design philosophy emphasizes code readability with the use of significant indentation."

In [78]:
sentence_no_stopwords = ' '.join([word for word in sentence5.split() if word not in (en_stopwords)])

In [79]:
sentence_no_stopwords

'Its design philosophy emphasizes code readability use significant indentation.'

In [80]:
# removing stop word
en_stopwords.remove('with')

In [81]:
# # adding stop word
en_stopwords.append('use')

In [82]:
sentence_no_stopwords_custom = ' '.join([word for word in sentence5.split() if word not in (en_stopwords)])

In [83]:
sentence_no_stopwords_custom

'Its design philosophy emphasizes code readability with significant indentation.'

### Experiment 9

In [84]:
import nltk
from nltk.stem import PorterStemmer, LancasterStemmer

In [85]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\Dharm Singh
[nltk_data]     Saini\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [86]:
words = ["running", "flies", "happily", "jumps", "swimming"]

In [87]:
porter = PorterStemmer()
porter_stems = [porter.stem(word) for word in words]

In [88]:
lancaster = LancasterStemmer()

In [89]:
lancaster_stems = [lancaster.stem(word) for word in words]

In [90]:
print("Original Words:  ", words)
print("Porter Stems:    ", porter_stems)
print("Lancaster Stems: ", lancaster_stems)

Original Words:   ['running', 'flies', 'happily', 'jumps', 'swimming']
Porter Stems:     ['run', 'fli', 'happili', 'jump', 'swim']
Lancaster Stems:  ['run', 'fli', 'happy', 'jump', 'swim']

## Experiment 10

In [91]:
import nltk
from nltk.stem import SnowballStemmer, RegexpStemmer

In [92]:
words = ["runes", "happily", "jumping", "easily", "faster","going","walking"]

In [93]:
snowball = SnowballStemmer("english")

In [94]:
snowball_stems = [snowball.stem(word) for word in words]

In [95]:
regexp = RegexpStemmer('ing$|ly$|s$', min=4)

In [96]:
regexp_stems = [regexp.stem(word) for word in words]

In [97]:
print("Original Words:   ", words)
print("Snowball Stems:   ", snowball_stems)
print("Regexp Stems:     ", regexp_stems)

Original Words:    ['runes', 'happily', 'jumping', 'easily', 'faster', 'going', 'walking']
Snowball Stems:    ['rune', 'happili', 'jump', 'easili', 'faster', 'go', 'walk']
Regexp Stems:      ['rune', 'happi', 'jump', 'easi', 'faster', 'go', 'walk']